name: Bug
description: Report broken behavior with reproducible details.
title: "bug: "
labels:
  - type:bug
  - status:todo
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: Concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Provide exact steps.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      placeholder: Describe what should happen.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      placeholder: Describe what actually happens.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, shell, version, branch, and any relevant context.
      placeholder: |
        - OS:
        - Shell:
        - Version:
        - Branch:

  - type: textarea
    id: logs
    attributes:
      label: Logs and artifacts
      description: Stack traces, command output, screenshots, or recordings.
      placeholder: Paste logs or links.

  - type: input
    id: dependencies
    attributes:
      label: Dependencies
      description: Blocking issue numbers, if known.
      placeholder: "#12"
